name: Go CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: Which environment
        required: true
        options: 
        - dev
        - qs
        - prod
env:
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  GITHUB_SHA: ${GITHUB_SHA}
  WORKDIR: "${{ github.workspace }}"
  DB_PASSWORD: "${DB_PASSWORD}"

jobs:
  build:
    environment:
      name: "${{ inputs.ENVIRONMENT }}"
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: set db password
        run: echo ${DB_PASSWORD} > db/password.txt

      - name: see db/password.txt
        run: cat db/password.txt

      - name: set db password
        run: echo "artifactory pass is ${ARTIFACTORY_PASSWORD}"

      - name: Login to github package repository
        env:
          ARTIFACTORY_PASSWORD: "${{ secrets.ARTIFACTORY_PASSWORD }}"
        run: echo ${{ secrets.ARTIFACTORY_PASSWORD }} | docker login -u sherifkunch --password-stdin
      - name: Build backend
        run: ./build.sh ${ARTIFACTORY_PASSWORD} 

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    # in case you want to make the deploy  step manual
    #if: github.event_name == 'workflow_dispatch'  

    steps:
      - name: run
        run: pwd

 
