name: Go CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ARTIFACYORY_PASSWORD: ${{ secrets.ARTIFACYORY_PASSWORD }}
  GITHUB_SHA: ${GITHUB_SHA}

jobs:
  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: run
        run: pwd

 
