name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  ARTIFACYORY_PASSWORD: ${{ secrets.ARTIFACYORY_PASSWORD }}
  GITHUB_SHA: ${GITHUB_SHA}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build backend
        run: ./build.sh

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  

    steps:
      - name: run
        run: pwd

 
